name: build online web app
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: options-web
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: immersive-translate/next-translator
          # ref: official
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      #https://stackoverflow.com/questions/61919141/read-json-file-in-github-actions
      - id: set_var
        run: |
          content=`cat ./manifest.json`
          echo "::set-output name=version::$(echo $content | jq -r '.version')"
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Test
        run: make test
      - name: Build
        run: make prod-build
      - name: ls
        run: ls -l dist/userscript


      # check version is 3 digits x.x.1-9 or x.x.0
      - name: Check version
        id: check_version
        continue-on-error: true
        run: |
          if [[ "${{ steps.set_var.outputs.version }}" =~ ^[0-9]+\.[0-9]+\.[1-9][0-9]*$ ]]; then
            echo "Version is nightly"
          else
            echo "Version is release"
            exit 1
          fi

      - name: Clone public app repo
        run: git clone https://$PERSONAL_GITHUB_TOKEN@github.com/immersive-translate/app repo
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Clone public dash repo
        if: steps.check_version.outcome == 'success'
        run: git clone https://$PERSONAL_GITHUB_TOKEN@github.com/immersive-translate/dash dash-repo
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Clone public repo
        if: steps.check_version.outcome == 'success'
        run: git clone https://$PERSONAL_GITHUB_TOKEN@github.com/immersive-translate/immersive-translate public-repo
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: publish to public repo
        if: steps.check_version.outcome == 'success'
        run: make movedisttopublic
      - name: publish options to dash
        run: make movetodash

      - name: publish to app
        if: steps.check_version.outcome == 'success'
        run: make movetoapp

      - name: commit to app
        if: steps.check_version.outcome == 'success'
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          cd repo
          ls -l
          pwd
          ls -l dist

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git status

          git add dist

          git status
          git commit -m "update dist"
          git status
          git remote -v
          git push
      - name: commit to dash
        if: steps.check_version.outcome == 'success'
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          cd dash-repo
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dist
          git commit -m "update dist"
          git remote -v
          git push

      - name: commit to public
        if: steps.check_version.outcome == 'success'
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          cd public-repo
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs
          git add dist
          git commit -m "update dist"
          git remote -v
          git push

