name: Deploy develop Account Site to Cloudflare Pages
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - deploy-develop-account-site
jobs:
  deploy:
    name: Deploy to Cloudfalre Pages
    runs-on: ubuntu-latest
    concurrency: build-account-site
    steps:
      - uses: actions/checkout@v3
        with:
          repository: immersive-translate/site
          ref: develop
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      # check to main branch
      - run: git checkout main && git merge develop
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: ./package-lock.json
      - name: Build website
        run: npm i && cd account &&  npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.IMMERSIVE_CLOUDFLARE_API_TOKEN }}
          accountId: ${{secrets.IMMERSIVE_CLOUDFLARE_ACCOUNT_ID}}
          projectName: develop-immersive-accounts
          directory: account/dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
