name: Deploy develop feedproxy to Cloudflare worker
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - deploy-develop-feedproxy-site
jobs:
  deploy:
    name: Deploy to Cloudfalre Pages
    runs-on: ubuntu-latest
    concurrency: build-develop-readit-site
    steps:
      - uses: actions/checkout@v3
        with:
          repository: funstory-ai/imt-backends
          ref: develop

          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - run: git checkout -b main
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: ./package-lock.json

      - name: Install website
        run: npm i
      - name: Deploy
        run: make deployproxy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.IMMERSIVE_CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.IMMERSIVE_CLOUDFLARE_ACCOUNT_ID}}
      # - name: Deploy
      #   uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: ${{ secrets.IMMERSIVE_CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{secrets.IMMERSIVE_CLOUDFLARE_ACCOUNT_ID}}
      #     workingDirectory: readit
