name: Manual release chrome crx

on:
  workflow_dispatch:
    inputs:
      chrome:
        default: "0"
        description: "is publish to chrome crx to official site"
        type: string
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:

      - name: Check out extension repository code
        uses: actions/checkout@v3
        with:
          repository: immersive-translate/extension
          ref: 'feat/makeCrx'
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.3
      - name: set crx version and upload crx to cloudflare r2
        run: make crx crx_version=${{ github.event.inputs.chrome }}
        env:
          CLOUFLARE_AWS_ACCESS_KEY_ID: ${{ secrets.CLOUFLARE_AWS_ACCESS_KEY_ID }}
          CLOUFLARE_AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUFLARE_AWS_SECRET_ACCESS_KEY }}
      - name: commit to extension
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add default_config.json
          git commit -m "update default_config.json for crx version"
          git push origin feat/makeCrx
      - name: Clone config repo
        run: git clone https://$PERSONAL_GITHUB_TOKEN@github.com/immersive-translate/config config-repo
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: write the new crx version to default_config
        run: make generateconfig target=config-repo/dist/default_config.json
      - name: commit to config
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          cd config-repo
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dist/default_config.json
          git commit -m "update default_config.json"
          git remote -v
          git push origin